### ISSUE TITLE
Update the commit status API when a build fails

### ISSUE THREAD

**Issue by shiftkey** [half-ogre/qed#50]
Just ran [this build](http://half-ogre-qed.cloudapp.net/octokit/octokit.net/builds/355) and it finishes but doesn't update the build status [here](https://github.com/octokit/octokit.net/pull/219) - it's still "waiting to hear about it"

```
STEP: Getting HEAD's SHA.
Setting SHA to 7107dd463776144e1de0c095445e1d6333694ab8.
Done
```

```
STEP: Updating GitHub build status to Failure.
The build has no SHA; skipping.
Done
```

It's probably this thingy

**Comment by half-ogre** [comment]
I have a fix, just haven't pushed it up yet, sorry. Won't be until tomorrow.

**Comment by shiftkey** [comment]
All good, just capturing it before I forget
