### ISSUE TITLE
Can w

### ISSUE THREAD

**Issue by forki** [half-ogre/qed#63]

**Comment by shiftkey** [comment]
![381](https://f.cloud.github.com/assets/359239/1691627/080a7f06-5e66-11e3-9b8a-04f3596abe59.gif)

I guess something went wrong here. OH MY! THE SUSPENSE!

**Comment by forki** [comment]
oups.

![cqebx](https://f.cloud.github.com/assets/57396/1691731/1bf5c672-5e68-11e3-8a34-626e0d2b0c57.gif)

See https://github.com/fsharp/FAKE/issues/255
