### ISSUE TITLE
Unable to publish commit status to Pending

### ISSUE THREAD

**Issue by shiftkey** [half-ogre/qed#84]
Example: http://half-ogre-qed.cloudapp.net/octokit/octokit.net/builds/941

I think it's related to some Commit Status API changes. 

https://developer.github.com/v3/repos/statuses/

Cross-posted with Octokit.net issue: https://github.com/octokit/octokit.net/issues/490

**Comment by half-ogre** [comment]
This is probably the result of my leaving GitHub and my token being revoked. :cry: I'll see about fixing in the morning.
